const TestProductArray = [
  {
    id: 1,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "4 reviews",
    description: "MSI GeForce RTX 3070",
    specialPrice: "600$",
    DiscountedPrice: "560$",
  },
  {
    id: 2,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "12 reviews",
    description: "Nvidia GeForce RTX 3080 Ti",
    specialPrice: "300$",
    DiscountedPrice: "280$",
  },
  {
    id: 3,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "1 reviews",
    description: "AMD Radeon RX 6800",
    specialPrice: "620$",
    DiscountedPrice: "580$",
  },
  {
    id: 4,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "8 reviews",
    description: "MSI RTX 3090 Gaming X Trio",
    specialPrice: "460$",
  },
  {
    id: 5,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "90 reviews",
    description: "Nvidia GeForce GTX 1660 Ti",
    specialPrice: "750$",
    DiscountedPrice: "590$",
  },
  {
    id: 6,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "71 reviews",
    description: "Nvidia Quadro RTX 5000",
    specialPrice: "200$",
    DiscountedPrice: "60$",
  },
  {
    id: 7,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "52 reviews",
    description: "Gigabyte Aorus GeForce RTX 3080",
    specialPrice: "630$",
    DiscountedPrice: "500$",
  },
  {
    id: 8,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "13 reviews",
    description: "Nvidia Quadro RTX 4000",
    specialPrice: "530$",
    DiscountedPrice: "500$",
  },
  {
    id: 9,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "67 reviews",
    description: "Nintendo Switch Pro",
    specialPrice: "490$",
    DiscountedPrice: "360$",
  },
  {
    id: 10,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "96 reviews",
    description: "Sony PlayStation 4 Pro",
    specialPrice: "600$",
    DiscountedPrice: "520$",
  },
  {
    id: 11,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "42 reviews",
    description: "Sony PlayStation 5",
    specialPrice: "670$",
    DiscountedPrice: "590$",
  },
  {
    id: 12,
    stock: true,
    photo: "../../assets/images/TestProductPhoto.png",
    photo2: "../../assets/images/TestProductPhoto2.png",
    photo3: "../../assets/images/TestProductPhoto3.png",
    photo4: "../../assets/images/TestProductPhoto4.png",
    photo5: "../../assets/images/TestProductPhoto5.png",
    reviewCount: "29 reviews",
    description: "Mademax RS-1 Handheld Game Console",
    specialPrice: "590$",
    DiscountedPrice: "500$",
  },
];
