export const ArrayForLinks = [
  {
    title: "Information",
    value: [
      "About Us",
      "About Zip",
      "Privacy Policy",
      "Search",
      "Terms",
      "Orders and Returns",
      "Contact Us",
      "Advanced Search",
      "Newsletter Subscription",
    ],
  },
  {
    title: "PC Parts",
    value: [
      "CPUS",
      "Add On Cards",
      "Hard Drives (Internal)",
      "Graphic Cards",
      "Keyboards / Mice",
      "Cases / Power Supplies / Cooling",
      "RAM (Memory)",
      "Software",
      "Speakers / Headsets",
      "Motherboards",
    ],
  },
  {
    title: "Desktop PCs",
    value: [
      "Custom PCs",
      "Servers",
      "MSI All-In-One PCs",
      "HP/Compaq PCs",
      "ASUS PCs",
      "Tecs PCs",
    ],
  },
  {
    title: "Laptops",
    value: [
      "Evryday Use Notebooks",
      "MSI Workstation Series",
      "MSI Prestige Series",
      "Tablets and Pads",
      "Netbooks",
      "Infinity Gaming Notebooks",
    ],
  },
  {
    title: "Address",
    value: [
      "Address: 1234 Street Adress",
      "Phones: (00) 1234 5678",
      "Open Hours :",
      "Monday: 9:00 AM - 5:30 PM",
      "Thursday: 9:00 AM - 5:30 PM",
      "Friday: 9:00 AM - 6:00 PM",
      "Saturday: 11:00 AM - 5:00 PM",
      "E-mail: shop@email.com",
    ],
  },
];
